### ISSUE TITLE
Bug: Concatenate error

### ISSUE THREAD

**Issue by nancikennedy** [ckaczor/TillerTracker#1]
10x TillerTracker\TillerTracker-9.0.4.lua:494: attempt to concatenate local 'mat_name' (a nil value)
[string "@TillerTracker\TillerTracker-9.0.4.lua"]:494: in function `UpdateData'
[string "@TillerTracker\TillerTracker-9.0.4.lua"]:335: in function `OnLoaded'
[string "@TillerTracker\TillerTracker-9.0.4.lua"]:320: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by nancikennedy** [comment]
Still seeing this error:

15x Interface/AddOns/TillerTracker/TillerTracker.lua:498: attempt to concatenate local 'mat_name' (a nil value)
[string "@Interface/AddOns/TillerTracker/TillerTracker.lua"]:498: in function `UpdateData'
[string "@Interface/AddOns/TillerTracker/TillerTracker.lua"]:659: in function `?'
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by ckaczor** [comment]
This should finally be fixed with the latest version.  =)
