### ISSUE TITLE
Bug: GetFriendshipReputation error

### ISSUE THREAD

**Issue by nancikennedy** [ckaczor/TillerTracker#2]
On Retail, with 9.0.5 installed

2x Interface/AddOns/TillerTracker/TillerTracker.lua:376: attempt to call global 'GetFriendshipReputation' (a nil value)
[string "@Interface/AddOns/TillerTracker/TillerTracker.lua"]:376: in function `ReputationDone'
[string "@Interface/AddOns/TillerTracker/TillerTracker.lua"]:384: in function `AllReputationsDone'
[string "@Interface/AddOns/TillerTracker/TillerTracker.lua"]:236: in function <Interface/AddOns/TillerTracker/TillerTracker.lua:225>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...ace/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...ace/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

**Comment by ckaczor** [comment]
I hadn't had a chance to check out the Dragonflight pre-patch yet - should be fixed with the latest version.
